export const ANIME_OPTIONS = [
	"Naruto", "Bleach", "One Piece", "Dragon Ball Z", "Fairy Tail",
	"Fullmetal Alchemist: Brotherhood", "Death Note", "Neon Genesis Evangelion",
	"Cowboy Bebop", "Steins;Gate", "Code Geass", "JoJo's Bizarre Adventure",
	"Hunter x Hunter", "AOT", "JJK", "Demon Slayer", "MHA", "Haikyuu",
	"Tokyo Revengers", "Chainsaw Man", "Vinland Saga", "Spy x Family",
	"Blue Lock", "Mob Psycho 100", "One Punch Man", "Black Clover",
	"Dr. Stone", "Sword Art Online", "Re:Zero", "Overlord", "Shield Hero",
	"That Time I Got Reincarnated as a Slime", "Bocchi the Rock", "Oshi no Ko",
	"Frieren: Beyond Journey's End", "Dungeon Meshi", "Solo Leveling",
	"Kaiju No. 8", "Violet Evergarden", "Your Lie in April", "Other",
];

export const ALL_COUNTRIES = [
	"Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
	"Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
	"Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Côte d'Ivoire", "Cabo Verde",
	"Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo",
	"Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
	"Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland",
	"France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea",
	"Guinea-Bissau", "Guyana", "Haiti", "Holy See", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran",
	"Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati",
	"Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania",
	"Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius",
	"Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia",
	"Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway",
	"Oman", "Pakistan", "Palau", "Palestine State", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland",
	"Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
	"Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
	"Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland",
	"Syria", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey",
	"Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu",
	"Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe", "Worldwide"
];

export const STORE_OPTIONS = ["Amazon", "Flipkart", "Etsy", "eBay", "AliExpress", "Other"];

export const CATEGORY_OPTIONS = [
	"Clothing", "Electronics", "Posters", "Gadgets", "Figures", "Accessories", "Cosplay", "Other"
];

export const SUB_CATEGORY_MAP = {
	"Clothing": ["T-Shirts", "Hoodies", "Pants", "Jackets"],
	"Electronics": ["Mouse Pads", "Phone Cases", "Keyboards", "Headphones"],
	"Posters": ["Canvas Print", "Paper Poster", "Metal Print", "Framed Poster"],
	"Gadgets": ["Keychains", "Mugs", "Lamps"],
	"Figures": ["Action Figure", "Statue", "Funko Pop", "Nendoroid"],
	"Accessories": ["Necklace", "Bracelet", "Ring", "Earrings", "Bag"],
	"Cosplay": ["Costume", "Props", "Wigs"],
};

	export const CURRENCY_LIST = [
		{ code: "USD", symbol: "$",   name: "US Dollar" },
		{ code: "EUR", symbol: "€",   name: "Euro" },
		{ code: "GBP", symbol: "£",   name: "British Pound" },
		{ code: "JPY", symbol: "¥",   name: "Japanese Yen" },
		{ code: "INR", symbol: "₹",   name: "Indian Rupee" },
		{ code: "KRW", symbol: "₩",   name: "South Korean Won" },
		{ code: "CNY", symbol: "¥",   name: "Chinese Yuan" },
		{ code: "AUD", symbol: "A$",  name: "Australian Dollar" },
		{ code: "CAD", symbol: "C$",  name: "Canadian Dollar" },
		{ code: "CHF", symbol: "Fr",  name: "Swiss Franc" },
		{ code: "SEK", symbol: "kr",  name: "Swedish Krona" },
		{ code: "NOK", symbol: "kr",  name: "Norwegian Krone" },
		{ code: "DKK", symbol: "kr",  name: "Danish Krone" },
		{ code: "NZD", symbol: "NZ$", name: "New Zealand Dollar" },
		{ code: "SGD", symbol: "S$",  name: "Singapore Dollar" },
		{ code: "HKD", symbol: "HK$", name: "Hong Kong Dollar" },
		{ code: "MXN", symbol: "$",   name: "Mexican Peso" },
		{ code: "BRL", symbol: "R$",  name: "Brazilian Real" },
		{ code: "RUB", symbol: "₽",   name: "Russian Ruble" },
		{ code: "ZAR", symbol: "R",   name: "South African Rand" },
		{ code: "TRY", symbol: "₺",   name: "Turkish Lira" },
		{ code: "AED", symbol: "د.إ", name: "UAE Dirham" },
		{ code: "SAR", symbol: "﷼",   name: "Saudi Riyal" },
		{ code: "QAR", symbol: "﷼",   name: "Qatari Riyal" },
		{ code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar" },
		{ code: "BHD", symbol: ".د.ب",name: "Bahraini Dinar" },
		{ code: "OMR", symbol: "﷼",   name: "Omani Rial" },
		{ code: "JOD", symbol: "JD",  name: "Jordanian Dinar" },
		{ code: "EGP", symbol: "£",   name: "Egyptian Pound" },
		{ code: "PKR", symbol: "₨",   name: "Pakistani Rupee" },
		{ code: "BDT", symbol: "৳",   name: "Bangladeshi Taka" },
		{ code: "LKR", symbol: "₨",   name: "Sri Lankan Rupee" },
		{ code: "NPR", symbol: "₨",   name: "Nepalese Rupee" },
		{ code: "MMK", symbol: "K",   name: "Myanmar Kyat" },
		{ code: "THB", symbol: "฿",   name: "Thai Baht" },
		{ code: "VND", symbol: "₫",   name: "Vietnamese Dong" },
		{ code: "IDR", symbol: "Rp",  name: "Indonesian Rupiah" },
		{ code: "MYR", symbol: "RM",  name: "Malaysian Ringgit" },
		{ code: "PHP", symbol: "₱",   name: "Philippine Peso" },
		{ code: "TWD", symbol: "NT$", name: "Taiwan Dollar" },
		{ code: "HUF", symbol: "Ft",  name: "Hungarian Forint" },
		{ code: "PLN", symbol: "zł",  name: "Polish Zloty" },
		{ code: "CZK", symbol: "Kč",  name: "Czech Koruna" },
		{ code: "RON", symbol: "lei", name: "Romanian Leu" },
		{ code: "BGN", symbol: "лв",  name: "Bulgarian Lev" },
		{ code: "HRK", symbol: "kn",  name: "Croatian Kuna" },
		{ code: "ISK", symbol: "kr",  name: "Icelandic Króna" },
		{ code: "UAH", symbol: "₴",   name: "Ukrainian Hryvnia" },
		{ code: "ILS", symbol: "₪",   name: "Israeli Shekel" },
		{ code: "NGN", symbol: "₦",   name: "Nigerian Naira" },
		{ code: "KES", symbol: "KSh", name: "Kenyan Shilling" },
		{ code: "GHS", symbol: "₵",   name: "Ghanaian Cedi" },
		{ code: "ETB", symbol: "Br",  name: "Ethiopian Birr" },
		{ code: "TZS", symbol: "TSh", name: "Tanzanian Shilling" },
		{ code: "UGX", symbol: "USh", name: "Ugandan Shilling" },
		{ code: "MAD", symbol: "MAD", name: "Moroccan Dirham" },
		{ code: "TND", symbol: "DT",  name: "Tunisian Dinar" },
		{ code: "DZD", symbol: "دج",  name: "Algerian Dinar" },
		{ code: "LYD", symbol: "LD",  name: "Libyan Dinar" },
		{ code: "XOF", symbol: "CFA", name: "West African CFA Franc" },
		{ code: "XAF", symbol: "CFA", name: "Central African CFA Franc" },
		{ code: "MZN", symbol: "MT",  name: "Mozambican Metical" },
		{ code: "ZMW", symbol: "ZK",  name: "Zambian Kwacha" },
		{ code: "BWP", symbol: "P",   name: "Botswana Pula" },
		{ code: "MUR", symbol: "₨",   name: "Mauritian Rupee" },
		{ code: "SCR", symbol: "₨",   name: "Seychellois Rupee" },
		{ code: "IQD", symbol: "ع.د", name: "Iraqi Dinar" },
		{ code: "IRR", symbol: "﷼",   name: "Iranian Rial" },
		{ code: "LBP", symbol: "£",   name: "Lebanese Pound" },
		{ code: "SYP", symbol: "£",   name: "Syrian Pound" },
		{ code: "YER", symbol: "﷼",   name: "Yemeni Rial" },
		{ code: "AFN", symbol: "؋",   name: "Afghan Afghani" },
		{ code: "UZS", symbol: "лв",  name: "Uzbekistani Som" },
		{ code: "KZT", symbol: "₸",   name: "Kazakhstani Tenge" },
		{ code: "AZN", symbol: "₼",   name: "Azerbaijani Manat" },
		{ code: "GEL", symbol: "₾",   name: "Georgian Lari" },
		{ code: "AMD", symbol: "֏",   name: "Armenian Dram" },
		{ code: "TJS", symbol: "SM",  name: "Tajikistani Somoni" },
		{ code: "KGS", symbol: "лв",  name: "Kyrgystani Som" },
		{ code: "TMT", symbol: "T",   name: "Turkmenistani Manat" },
		{ code: "MNT", symbol: "₮",   name: "Mongolian Tögrög" },
		{ code: "KHR", symbol: "៛",   name: "Cambodian Riel" },
		{ code: "LAK", symbol: "₭",   name: "Laotian Kip" },
		{ code: "BND", symbol: "$",   name: "Brunei Dollar" },
		{ code: "MOP", symbol: "P",   name: "Macanese Pataca" },
		{ code: "MVR", symbol: "Rf",  name: "Maldivian Rufiyaa" },
		{ code: "BTN", symbol: "Nu",  name: "Bhutanese Ngultrum" },
		{ code: "PGK", symbol: "K",   name: "Papua New Guinean Kina" },
		{ code: "FJD", symbol: "FJ$", name: "Fijian Dollar" },
		{ code: "SBD", symbol: "SI$", name: "Solomon Islands Dollar" },
		{ code: "VUV", symbol: "VT",  name: "Vanuatu Vatu" },
		{ code: "WST", symbol: "WS$", name: "Samoan Tālā" },
		{ code: "TOP", symbol: "T$",  name: "Tongan Paʻanga" },
		{ code: "PEN", symbol: "S/.", name: "Peruvian Sol" },
		{ code: "COP", symbol: "$",   name: "Colombian Peso" },
		{ code: "ARS", symbol: "$",   name: "Argentine Peso" },
		{ code: "CLP", symbol: "$",   name: "Chilean Peso" },
		{ code: "UYU", symbol: "$U",  name: "Uruguayan Peso" },
		{ code: "PYG", symbol: "Gs",  name: "Paraguayan Guaraní" },
		{ code: "BOB", symbol: "Bs.", name: "Bolivian Boliviano" },
		{ code: "VES", symbol: "Bs.S",name: "Venezuelan Bolívar" },
		{ code: "GYD", symbol: "$",   name: "Guyanese Dollar" },
		{ code: "SRD", symbol: "$",   name: "Surinamese Dollar" },
		{ code: "TTD", symbol: "TT$", name: "Trinidad Dollar" },
		{ code: "JMD", symbol: "J$",  name: "Jamaican Dollar" },
		{ code: "BBD", symbol: "Bds$",name: "Barbadian Dollar" },
		{ code: "HTG", symbol: "G",   name: "Haitian Gourde" },
		{ code: "CUP", symbol: "₱",   name: "Cuban Peso" },
		{ code: "DOP", symbol: "RD$", name: "Dominican Peso" },
		{ code: "GTQ", symbol: "Q",   name: "Guatemalan Quetzal" },
		{ code: "HNL", symbol: "L",   name: "Honduran Lempira" },
		{ code: "NIO", symbol: "C$",  name: "Nicaraguan Córdoba" },
		{ code: "CRC", symbol: "₡",   name: "Costa Rican Colón" },
		{ code: "PAB", symbol: "B/.", name: "Panamanian Balboa" },
		{ code: "ALL", symbol: "L",   name: "Albanian Lek" },
		{ code: "MKD", symbol: "ден", name: "Macedonian Denar" },
		{ code: "BAM", symbol: "KM",  name: "Bosnia-Herzegovina Mark" },
		{ code: "RSD", symbol: "din", name: "Serbian Dinar" },
		{ code: "MDL", symbol: "L",   name: "Moldovan Leu" },
		{ code: "BYN", symbol: "Br",  name: "Belarusian Ruble" },
		{ code: "LTL", symbol: "Lt",  name: "Lithuanian Litas" },
		{ code: "LVL", symbol: "Ls",  name: "Latvian Lats" },
		{ code: "EEK", symbol: "kr",  name: "Estonian Kroon" },
	];

	export const CURRENCY_SYMBOL_MAP = CURRENCY_LIST.reduce((acc, c) => { acc[c.code] = c.symbol; return acc; }, {});